### ISSUE TITLE
OnError handler can be customized

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/botframework-core#11]
Default exception handling should have the following behavior:
1. Log to telemetry
    - Boolean flag that sends stack trace content to configured telemetry provider, if enabled. Likely enabled for both dev and prod.
1. Error message configuration
    - Users shouldn't have to modify the runtime to add their error messages. Instead, provide reference to an LG template/file with error messages that would be used.
1. Send trace activity
    - Boolean flag that sends stack trace content as a trace activity to the user. This is helpful for dev environments but likely wouldn't be enabled on production.
1. Clear conversation state
    - Logic enabled in code that should be expected and not customizable.

**Comment by peterinnesmsft** [comment]
Follow up with Lauren Mills and Elaine Chang to determine requirements around extensibility, as this is being driven as an ask from the Skills team. For example, Application Insights handling, etc.

**Comment by ryanlengel** [comment]
After syncing with the Skills team I've added requirements in the initial post, will continue to expand on them
