### ISSUE TITLE
Definition of Core library

### ISSUE THREAD

**Issue by ryanlengel** [microsoft/botframework-core#2]
.NET code project for a bot available as a library, this does not produce an application on itself.

- [x] Rename namespace/classes to Core/Runtime appropriate
- [x] Pull out and generalize Composer-specific settings
- [ ] Enables low-code startup of host application using standardized application configuration

**Comment by peterinnesmsft** [comment]
Create a separate issue to track publishing Microsoft.Bot.Core as a separate NuGet package to MyGet.
