### ISSUE TITLE
Define and implement replacement of RemoveRecipientMention feature

### ISSUE THREAD

**Issue by ryanlengel** [microsoft/botframework-core#20]
RemoveRecipientMention appears to be a Teams-related Activity extension that removes @mentions in , this should be decoupled from the core runtime and available as a middleware.

https://github.com/microsoft/botframework-core/blob/80274609e5b59c72d3d44cc79eb7de594fd3949f/src/Microsoft.Bot.Core/CoreBot.cs#L67

https://github.com/microsoft/botframework-core/blob/80274609e5b59c72d3d44cc79eb7de594fd3949f/src/Microsoft.Bot.Core/CoreBot.cs#L82-L85

Original request from microsoft/BotFramework-Composer#3104

**Comment by tracyboehrer** [comment]
Technically, each channel has a different mention format.  i.e., Slack, Teams, Telegram, etc...
