### ISSUE TITLE
Refactor bot path adapter

### ISSUE THREAD

**Issue by ryanlengel** [microsoft/botframework-core#22]
Runtime should consume bot path value through application setting, per environment.

https://github.com/microsoft/botframework-core/blob/80274609e5b59c72d3d44cc79eb7de594fd3949f/src/Microsoft.Bot.Core/CoreBotPathExtensions.cs#L16-L32

**Comment by peterinnesmsft** [comment]
This is tied to the project directory restructure - we are otherwise tightly coupled to Composer for the time being. Ideally, the build output/publish folder inherently should always serve as the root from which to discover declarative files, etc.
