### ISSUE TITLE
Evaluate WebHost as a Functions App

### ISSUE THREAD

**Issue by ryanlengel** [microsoft/botframework-core#29]
Option 1: Provide a single Web Host application that enables a user to toggle between Azure Web App or Azure Functions
In this scenario, a user has a package reference or the source to a low-code application that largely has the same bot behavior as a web app, but the endpoints are triggers rather than controllers. The user can toggle which option they are using in their application settings.

Option 2: Provide separate Web Host applications  
In this scenario, a user selects either the Functions or WebApp (default) variant of WebHost. If they only have a package reference to WebHost, they can switch between one or the other and maintain the same bot functionality that is passed in through declarative configuration. If they have the source code, they can download a template of the other option and replace.

**Comment by tracyboehrer** [comment]
With #58, Functions have been added.  The current state is more like Option #2, except as code (not a package).  Given that Webapp is an app, and Functions is a library, it's not clear how Option 1 would work.

What likely remains is: Does the code for webapp/functions exist in a package?  i.e., For webapp the Controllers, and for Functions the Triggers (and other stuff).  Or is it just part of the scaffolding template?

**Comment by tracyboehrer** [comment]
This will be provided by two host projects to be consumed as a template.  Microsoft.Bot.Builder.Runtime.WebHost and Microsoft.Bot.Builder.Runtime.FunctionHost.  Each will contain the csproj, Program.cs, Startup.cs, Triggers/Controllers, and a dependency on the Runtime package.
