### ISSUE TITLE
Definition of runtime solution architecture

### ISSUE THREAD

**Issue by ryanlengel** [microsoft/botframework-core#3]
### "Ejected runtime" output
_When Microsoft.Bot.Core is published_

```
MyBot/
    runtime/
        build/
        src/
            app/
                MyBot.App.csproj
            customaction/
                MyBot.CustomAction.csproj
            tests/
                MyBot.Tests.csproj
        MyBot.sln
```

* `build/` - Build scripts, deployment scripts, CI/CD scripts
* `src/` - Runtime source code
* `MyBot.App` - My bot application (azurewebapp, azurefunctions, etc.) using my bot's name
* `MyBot.CustomAction` - Sample Custom Action project I can use to write my own and reference from
* `MyBot.Tests` - Unit tests for my bot application

**Comment by tracyboehrer** [comment]
{​​​​​​​name}​​​​​​​/.............................................

    {​​​​​​​name}​​​​​​​.botproj..................................

    {​​​​​​​name}​​​​​​​.sln......................................

    {​​​​​​​name}​​​​​​​/.........................................

        {​​​​​​​name}​​​​​​​.csproj...............................

        appsettings.json............................

        Program.cs..................................

        runtime.json................................

        Startup.cs..................................

        Controllers/................................

            BotController.cs........................

            SkillController.cs......................

        dialogs/....................................

            {​​​​​​​dialogName}​​​​​​​/...........................

                {​​​​​​​dialogName}​​​​​​​.dialog.................

                knowledge-base/.....................

                    {​​​​​​​locale}​​​​​​​/.......................

                        {​​​​​​​dialogName}​​​​​​​.{​​​​​​​locale}​​​​​​​.qna...

                language-generation/................

                    {​​​​​​​locale}​​​​​​​/.......................

                        {​​​​​​​dialogName}​​​​​​​.{​​​​​​​locale}​​​​​​​.lg....

                language-understanding/.............

                    {​​​​​​​locale}​​​​​​​/.......................

                        {​​​​​​​dialogName}​​​​​​​.{​​​​​​​locale}​​​​​​​.lu....

        Properties/.................................

            launchSettings.json.....................

        Scripts/....................................

            deploy.ps1..............................

        wwwroot/....................................

            default.htm.............................

**Comment by ryanlengel** [comment]
Closed as we have the generator outputting the new runtime structure
